### ISSUE TITLE
error running 'wp composer'

### ISSUE THREAD

**Issue by selfagency** [srtfisher/wp-composer#1]
hi, i receive the following error after installing and activating the plugin using `wp plugin install composer --activate` and attempting to run `wp composer`. the file it seems to be referencing, `wp-cli-composer-command.php` definitely doesn't appear to exist in the `plugins/composer` folder.

`PHP Warning:  require_once(/Users/daniel/Dev/cjnv/wp-content/plugins/composer/wp-cli-composer-command.php): failed to open stream: No such file or directory in /Users/daniel/Dev/cjnv/wp-content/plugins/composer/composer.php on line 25
Warning: require_once(/Users/daniel/Dev/cjnv/wp-content/plugins/composer/wp-cli-composer-command.php): failed to open stream: No such file or directory in /Users/daniel/Dev/cjnv/wp-content/plugins/composer/composer.php on line 25
PHP Fatal error:  require_once(): Failed opening required '/Users/daniel/Dev/cjnv/wp-content/plugins/composer/wp-cli-composer-command.php' (include_path='/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/php-token-stream:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/phpunit-mock-objects:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/php-code-coverage:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/phpunit:/usr/local/Cellar/wp-cli/0.22.0/vendor/symfony/yaml:.:') in /Users/daniel/Dev/cjnv/wp-content/plugins/composer/composer.php on line 25
Fatal error: require_once(): Failed opening required '/Users/daniel/Dev/cjnv/wp-content/plugins/composer/wp-cli-composer-command.php' (include_path='/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/php-token-stream:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/phpunit-mock-objects:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/php-code-coverage:/usr/local/Cellar/wp-cli/0.22.0/vendor/phpunit/phpunit:/usr/local/Cellar/wp-cli/0.22.0/vendor/symfony/yaml:.:') in /Users/daniel/Dev/cjnv/wp-content/plugins/composer/composer.php on line 25`

**Comment by rbvea** [comment]
+1

**Comment by ankurk91** [comment]
If you download this plugin from https://wordpress.org/plugins/composer/
You will notice that it contain a file `run.php` but it should be `wp-cli-composer-command.php`
So go and manually rename this file then try activating the plugin.
